### ISSUE TITLE
Receiving Error Code 429 results in empty predictions

### ISSUE THREAD

**Issue by adamcatto** [dchary/ucdeconvolve#1]
It seems that in around 10% of the batches, I receive error code 429 (too many requests) which results in an empty prediction set for those batches. Aside from not getting predictions for these batches, the shape of the empty predictions does not match the shape of the successful predictions (dimensionality is that of original count matrix), therefore cannot concatenate the returned dataframes. Here is a traceback (wrote some code to count the shapes of returned prediction dataframes):

```
/home/lauren/anaconda3/envs/single_cell/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
2022-12-02 17:03:19,648|[UCD]|INFO: Starting UniCell Deconvolve Run.
2022-12-02 17:03:19,782|[UCD]|DEBUG: Using batchsize: 256 on dataset of shape: (38354, 32285)
2022-12-02 17:03:19,782|[UCD]|DEBUG: Data will be sent in 150 packet(s), each split into 4 sub-buffers of at most ~64 samples.
2022-12-02 17:03:19,782|[UCD]|DEBUG: Data pipeline ready.
2022-12-02 17:03:19,782|[UCD]|INFO: Initiating data stream for prediction.
 62% (93 of 149) |####################################################                                | Elapsed Time: 0:01:24 ETA:   0:02:282022-12-02 17:06:09,302|[UCD]|ERROR: Fatal error sending packet, returning empty predictions.
 68% (102 of 149) |########################################################                           | Elapsed Time: 0:01:31 ETA:   0:00:442022-12-02 17:06:15,662|[UCD]|ERROR: Fatal error sending packet, returning empty predictions.
2022-12-02 17:06:18,394|[UCD]|ERROR: Fatal error sending packet, returning empty predictions.
 81% (121 of 149) |###################################################################                | Elapsed Time: 0:01:49 ETA:   0:00:312022-12-02 17:06:34,134|[UCD]|ERROR: Fatal error sending packet, returning empty predictions.
 82% (123 of 149) |####################################################################               | Elapsed Time: 0:01:50 ETA:   0:00:222022-12-02 17:06:35,180|[UCD]|ERROR: Fatal error sending packet, returning empty predictions.
2022-12-02 17:06:35,535|[UCD]|ERROR: Fatal error sending packet, returning empty predictions.
 88% (132 of 149) |#########################################################################          | Elapsed Time: 0:01:57 ETA:   0:00:102022-12-02 17:06:41,664|[UCD]|ERROR: Fatal error sending packet, returning empty predictions.
2022-12-02 17:06:42,045|[UCD]|ERROR: Fatal error sending packet, returning empty predictions.
 89% (133 of 149) |##########################################################################         | Elapsed Time: 0:01:58 ETA:   0:00:102022-12-02 17:06:42,859|[UCD]|ERROR: Fatal error sending packet, returning empty predictions.
 95% (142 of 149) |###############################################################################    | Elapsed Time: 0:02:04 ETA:   0:00:032022-12-02 17:06:48,486|[UCD]|ERROR: Fatal error sending packet, returning empty predictions.
2022-12-02 17:06:48,597|[UCD]|ERROR: Fatal error sending packet, returning empty predictions.
100% (149 of 149) |###################################################################################| Elapsed Time: 0:02:08 Time:  0:02:08
Prediction shapes across predictions list:
Counter({(256, 842): 138, (256, 28867): 11, (210, 842): 1})
2022-12-02 17:06:52,797|[UCD]|INFO: Data streaming complete.
2022-12-02 17:06:52,798|[UCD]|DEBUG: Streaming time: 213.015 (sec)
2022-12-02 17:06:52,798|[UCD]|DEBUG: Streaming rate: 180.053 (samples / sec)
Traceback (most recent call last):
  File "/d1/studies/Lauren/Collaborations/JunShi/JunShiIPN/outs/count/ucdeconvolve_test.py", line 8, in <module>
    ucd.tl.deconvolve(adata, API_KEY, showprogress = True, verbosity = logging.DEBUG)
  File "/home/lauren/anaconda3/envs/single_cell/lib/python3.9/site-packages/ucdeconvolve/_tools/_tools.py", line 198, in deconvolve
    predictions = np.concatenate(predictions)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 842 and the array at index 99 has size 28867
```
I managed to resolve this issue by providing an additional exception handler in `ucdeconvolve/_io.py`:

```python
import time
# ... other imports

def post_online_prediction (...)
# ...
            elif response.status_code == 503:
                # Report status that service is busy
                ucdlogger.error(f"Failed status code {response.status_code}," + \
                                "service in high-demend, consider reducing threads or try again later. returning empty predictions.")

            elif response.status_code == 429:
                time.sleep(1)
                post_online_prediction(
                    packet,
                    token,
                    max_retries,
                    retry_backoff_factor,
                    timeout
                )
````

Essentially just wait an appropriate amount of time upon receiving the "too many requests" error (in this case 1 second) and try again. This completely resolved the issue for me.

**Comment by dchary** [comment]
Thank you for bringing up this issue. The latest update features a more robust time-out strategy using urrlib3 Retry. Each prediction request will now automatically attempt to re-send up to 6 times in stepwise fashion with increasing delays between each successive retry up to a delay of ~ 1-minute. In testing this under load this seems to resolve the timeout problems. In the even a prediction packet still fails, UCD now handles these failures gracefully and will return NaN for that packet alone, so any successful predictions are not lost. Any loss is reported by the debugger under the warning flag.
