### ISSUE TITLE
Error code 500

### ISSUE THREAD

**Issue by macsennett** [dchary/ucdeconvolve#2]
Hi Daniel, 

When attempting to run UCD I'm getting the following error: 

```
ucd.tl.deconvolve(data, token = 'removed', batchsize = 256, n_threads = 1, showprogress = True, verbosity = logging.DEBUG)
```

```
Traceback (most recent call last):
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  [Previous line repeated 3 more times]
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ucd6-7ohn2lw6.uc.gateway.dev', port=443): Max retries exceeded with url: /deconvolve (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "{removed}/scripts/unicellDecon.py", line 13, in <module>
    ucd.tl.deconvolve(adata, token = {removed}, 
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/ucdeconvolve/_tools/_tools.py", line 186, in deconvolve
    predictions = list(pbar(executor.map(predict, dataset), max_value = n_iter))
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/progressbar/shortcuts.py", line 10, in progressbar
    for result in progressbar(iterator):
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/progressbar/bar.py", line 554, in __next__
    value = next(self._iterable)
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/ucdeconvolve/_io.py", line 114, in post_online_prediction
    raise e
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/ucdeconvolve/_io.py", line 81, in post_online_prediction
    response = session.send(request.prepare(), timeout = timeout)
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/macsennett/opt/miniconda3/envs/unicell/lib/python3.10/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='ucd6-7ohn2lw6.uc.gateway.dev', port=443): Max retries exceeded with url: /deconvolve (Caused by ResponseError('too many 500 error responses'))
```

data is an AnnData object containing bulk RNA-seq data.

**Comment by dchary** [comment]
Hi @macsennett , thanks for the report. I would suggest lowering the batchsize for each request down to 8 or 16 and retry. Batch defaults were set assuming expression profiles are fairly sparse (i.e. scRNA-Seq or visium spatial data), which is not the case with bulk samples. There is an inherent backend limitation on the absolute size of prediction requests per batch, so my suspicion is that our prediction backend service is kicking back the request. We will be patching this issue in an large update we are going to be pushing out very soon. Please let me know if that resolves the issue! Thanks!

**Comment by macsennett** [comment]
That fixed it, thanks!
